### ISSUE TITLE
请问，你的java Library是怎么生成jar的?

### ISSUE THREAD

**Issue by EthanCo** [justinhjq/BubbleAno#1]
请问，你的java Library是怎么生成jar的? 为什么我新建的Java Library，生成的jar包放到新建的Android项目中后，报
Error:Execution failed for task ':bubblesdemo:transformClassesWithDexForDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\Develop\jdk1.8.0_66\bin\java.exe'' finished with non-zero exit value 1错误

**Comment by justinhjq** [comment]
你的jdk版本是1.8.0的，不兼容的，jdk版本降低到1.7.x就ok了～

**Comment by EthanCo** [comment]
非常感谢 ! 终于可以运行了 ~
